Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "user"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "user"
        vb.memory = 3072
    end
    config.vm.network "private_network", ip: "192.168.42.110"
    config.vm.provision "shell", privileged: false, path: "./scripts/setup.sh"
end